### ISSUE TITLE
更新机制的疑问

### ISSUE THREAD

**Issue by luckydrq** [mobframe/mobile-front-end-info-collection#14]
hi，仓库里的周刊日期只到2014.11.10，后来看到issue里继续更新了，以后都用issue的方式更新么？我本想写个chrome插件订阅的，想确认下更新机制，谢谢！

**Comment by demohi** [comment]
感谢关注，我们目前通过 issue 更新

如果想订阅的话，欢迎关注我们的微信公众号  Web 开发技术周刊

**Comment by mobframe** [comment]
我整理一下，把以前的内容都放到issue里来，并删除以前的git内容

**Comment by demohi** [comment]
:+1:
