### ISSUE TITLE
2015-05-11

### ISSUE THREAD

**Issue by demohi** [mobframe/mobile-front-end-info-collection#37]
[React直出实现与原理](https://github.com/miniflycn/qvd/issues/2)

> 这篇文章我们来讲讲React的直出。
比起MVVM，React比较容易实现直出，那么React的直出是如何实现，有什么值得我们学习的呢

**Comment by zezhou** [comment]
[Node.js下自定义错误类型](https://cnodejs.org/topic/52090bc944e76d216af25f6f)

> 一般来说，很少人会考虑如何处理应用产生的错误的策略，调试的过程中，简单地利用console.log(‘error’)定位错误，基本够用了，通过留下这些调试信息，能够为我们以后的调试过程中升了不少时间，提高了维护性。所以错误提示非常重要。同时，也会带来一些比较糟糕用法。

**Comment by demohi** [comment]
[React中的Transaction模型](https://github.com/miniflycn/qvd/issues/3)

> React中的Transaction 介绍

**Comment by zezhou** [comment]
[co 函数库的含义和用法](http://www.ruanyifeng.com/blog/2015/05/co.html)

> co 函数库是著名程序员 TJ Holowaychuk 于2013年6月发布的一个小工具，用于 Generator 函数的自动执行。本文介绍了该内容

**Comment by zezhou** [comment]
[async 函数的含义和用法](http://www.ruanyifeng.com/blog/2015/05/async.html)

> 异步操作是 JavaScript 编程的麻烦事，麻烦到一直有人提出各种各样的方案，试图解决这个问题。
从最早的回调函数，到 Promise 对象，再到 Generator 函数，每次都有所改进，但又让人觉得不彻底。它们都有额外的复杂性，都需要理解抽象的底层运行机制。异步I/O不就是读取一个文件吗，干嘛要搞得这么复杂？异步编程的最高境界，就是根本不用关心它是不是异步。async 函数就是隧道尽头的亮光，很多人认为它是异步操作的终极解决方案。
