### ISSUE TITLE
2015-06-15

### ISSUE THREAD

**Issue by jabez128** [mobframe/mobile-front-end-info-collection#42]
[Waht is Code](http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/)

> 平实的语言和华丽的交互效果，让读者重新认识 "What is Code"

**Comment by zezhou** [comment]
[拥抱约束](http://mp.weixin.qq.com/s?__biz=MzA3NDM0ODQwMw==&mid=208859872&idx=1&sn=0b3efde37aefc57d9603bd214b9a76f0&3rd=MzA3MDU4NTYzMw==&scene=6#rd)

> 很多时候，我们做系统，一开始对系统的潜在的约束条件并无深刻体会。做着做着，发现有了约束，于是在设计里打个补丁，继续前行，这样的补丁会越来越多，最终成了托勒密的地心说天体模型：越来越复杂的结构只是为了应对越来越多的 "exception"，最终变成一个臃肿的夹杂着各种 corner case 的怪胎，从而不得不推倒重来。任何产品或者工具都是有 trade-off 的。约束条件并非坏事，它让你更清晰地考虑系统的设计，从而做出更好的选择。

**Comment by zezhou** [comment]
(H5页面的跨webview预拉取数据尝试 )[http://www.alloyteam.com/2015/06/h5-ye-mian-di-kua-webview-yu-la-qu-shu-ju-chang-shi/]

> 安卓上利用调起应用时1秒钟的间隔预拉取数据的优化

**Comment by zezhou** [comment]
[移动web问题小结](http://www.alloyteam.com/2015/06/yi-dong-web-wen-ti-xiao-jie/)

> 总结了移动开发中常见的问题和解决方法

**Comment by zezhou** [comment]
[The state of Web Components](https://hacks.mozilla.org/2015/06/the-state-of-web-components/)

> 自从2011年出现 Web Components 概念后，时间已经过去了5年。Web Components 在实际应用中是什么情况？各浏览器对其支持达到了什么程度？本文就介绍了相关内容。
