### ISSUE TITLE
2016-01-11 weekly

### ISSUE THREAD

**Issue by chasonw** [mobframe/mobile-front-end-info-collection#73]
[MySQL 加锁处理分析](http://hedengcheng.com/?p=771) 

> 深入浅出介绍MySQL 加锁机制。

**Comment by jabez128** [comment]
[饿了么移动APP的架构演进](https://mp.weixin.qq.com/s?__biz=MzAxNDUwMzU3Mw==&mid=401044540&idx=1&sn=24b7d8fb655ae6dd5d989d0cb3c08e90)

>  饿了么web APP 架构演变史

**Comment by zezhou** [comment]
[vue、react和angular 2.x谁是2016年的主流？](https://www.zhihu.com/collection/20393676)

> 大家讨论了对 vue, react 和 angular 这三个框架未来的看法

**Comment by zezhou** [comment]
[找回 Node.js 里面那些遗失的 ES6 特性](http://taobaofed.org/blog/2016/01/07/find-back-the-lost-es6-features-in-nodejs/)

> 介绍了node.js 已经支持，正在测试，即将支持的 es6 特性

**Comment by zezhou** [comment]
[iOS开发系列--让你的应用“动”起来](http://www.cnblogs.com/kenshincui/p/3972100.html)

> 在iOS中随处都可以看到绚丽的动画效果，实现这些动画的过程并不复杂，今天将带大家一窥iOS动画全貌。在这里你可以看到iOS中如何使用图层精简非交互式绘图，如何通过核心动画创建基础动画、关键帧动画、动画组、转场动画，如何通过UIView的装饰方法对这些动画操作进行简化等。在今天的文章里您可以看到动画操作在iOS中是如何简单和高效，很多原来想做但是苦于没有思路的动画在iOS中将变得越发简单

**Comment by zezhou** [comment]
[如何让iOS 保持界面流畅？这些技巧你知道吗](http://www.cocoachina.com/ios/20151130/14477.html?from=timeline&isappinstalled=0)

> 这篇文章会非常详细的分析 iOS 界面构建中的各种性能问题以及对应的解决思路，同时给出一个开源的微博列表实现，通过实际的代码展示如何构建流畅的交互。

**Comment by Blet** [comment]
vue、react和angular 2.x谁是2016年的主流？ 链接是否有点不明确   https://www.zhihu.com/question/38989845 应该是这个吧

**Comment by zezhou** [comment]
[RecyclerView使用详解（一）](http://frank-zhu.github.io/android/2015/01/16/android-recyclerview-part-1/)

> RecyclerView是谷歌在Android L中引入的一个高效的List View的控件，并且在V7的包中作兼容RecyclerView的优势：对过程管理更规范：内置了标准的ViewHolder，考虑了之前AbsListView自定义ViewHolder的不足，并且确定一个ViewHolder对应于一个View；多方向控制：水平方向和竖直方向；支持ViewType的非递增变化，这个变化使得RecyclerView的内存开销大大小于ListView，在ViewType很多的情况；ListView的优势：ListView对ViewType很少且固定的情况，使用更加高效，且更稳定。
