### ISSUE TITLE
2016-04-25 weekly

### ISSUE THREAD

**Issue by changfuguo** [mobframe/mobile-front-end-info-collection#87]
[谷歌设计师 Material Design 设计过程心得（多图）](http://daily.zhihu.com/story/4077135)

> 分享对于Material Design的一些设计性思考。

**Comment by viRingbells** [comment]
[Node源码详解](http://www.cnblogs.com/papertree/p/5225009.html)

> 一篇对nodejs源码的分析解毒，详细的解毒了node从os到C++到js的整个过程，事件循环、io等功能的原理和代码实现。不过貌似还在更新中。

**Comment by jabez128** [comment]
[WebGL 技术储备指南](http://taobaofed.org/blog/2015/12/21/webgl-handbook/)

> WebGL开发技术储备汇总

**Comment by jabez128** [comment]
[命令行的艺术](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)

> 常用命令行工具、技巧大全

**Comment by zezhou** [comment]
[【译】2016React大会之React展望](http://www.alloyteam.com/2016/04/reactjs2016-what-lies-ahead/)
> 2016年React.js大会在今年1月份举行，2月底放出了视频，本文翻译的是其中一个演讲What Lies Ahead,介绍了React目前的进展，以及未来的研发方向。

**Comment by zezhou** [comment]
[无线性能优化：Composite](http://taobaofed.org/blog/2016/04/25/performance-composite/)

> 深入浏览器低层，并在渲染层合并（composite）这一环节提出了优化建议。

**Comment by zezhou** [comment]
[React Native: A year in review](https://code.facebook.com/posts/597378980427792/react-native-a-year-in-review)

> React Native 开发团队介绍了 React Native 怎么从一个内部的 hackathon 项目成长成为移动开发领域新的明星技术的发展历程。另外还介绍了React Native 项目在公司内的应用情况，team的情况等八卦。本文是一篇关于技术创新的最佳实践。需翻墙阅读。
